### ISSUE TITLE
cmd/go-post: "assignbinop: erroneous conversion of `int - var`"

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#175]
_From @karlek on May 29, 2015 13:53_

``` go
package main

func main() {
    dx := 1

    // go-post wants to change this to:
    // dx -= 0 which is wrong.
    dx = 0 - dx

    // dx -= 0         = 1
    // dx = 0 - dx     = -1
}
```

If the line had been 0 + dx it would be correct, however statements with subtraction are erroneously converted.

_Copied from original issue: decomp/go-post#1_

**Comment by mewmew** [comment]
Good catch! I'll take a look at it.

Föresten, glömde du din nyckel bror?

**Comment by mewmew** [comment]
P.S. Gotta love that GitHub is our most effective means of remote communication :)

**Comment by mewmew** [comment]
_From @karlek on May 29, 2015 13:56_

Sweet! I'll try to make a fork which ignores import blocks 

:camel: Nop, have my keys here :) Haha, yup! Tänkte tagga hem, nu ska du dra snart?

**Comment by mewmew** [comment]
_From @karlek on May 29, 2015 13:58_

Daniel undrar var du är? :P

**Comment by mewmew** [comment]
> I'll try to make a fork which ignores import blocks 

Could you clarify what you mean by ignoring import blocks? Do they currently cause an issue?

> Nop, have my keys here :) Haha, yup! Tänkte tagga hem, nu ska du dra snart?

Bra. Såg nycklarna på bordet, därav funderingen. Jag rullar nog inom den närmsta timmen eller så. Vi kanske hinner ses i några min.

> Daniel undrar var du är? :P

Haha :) Jag är i hagis. Drar mig mot Fruängen om 1h eller så.

**Comment by mewmew** [comment]
_From @karlek on May 29, 2015 13:59_

``` go
package main

import (
    "fmt"
)

func main() {
    dx := 1
    // go-post wants to change this to:
    // dx -= 0 which is wrong.
    dx = 0 + dx

    // dx -= 0         = 1
    // dx = 0 - dx     = -1
    fmt.Println(dx)
}
```

Gets a runtime error:

``` go
panic: illegal line number (line numbering starts at 1)

goroutine 1 [running]:
go/token.(*File).MergeLine(0x0, 0x0)
    /usr/lib/go/src/go/token/position.go:144 +0x6f
golang.org/x/tools/go/ast/astutil.DeleteImport(0xc208034340, 0xc208068080, 0x596290, 0x2, 0x7ffe68e66c01)
    /home/_/Dropbox/comp/go/src/golang.org/x/tools/go/ast/astutil/imports.go:188 +0xb89
main.mainret(0xc208068080, 0x7ffe68e66c00)
    /home/_/Dropbox/comp/go/src/decomp.org/x/cmd/go-post/mainret.go:94 +0x14e
main.processFile(0x7ffe68e66cf0, 0x4, 0x7f6e3b139b00, 0x0, 0x0)
    /home/_/Dropbox/comp/go/src/decomp.org/x/cmd/go-post/main.go:147 +0xaed
main.main()
    /home/_/Dropbox/comp/go/src/decomp.org/x/cmd/go-post/main.go:96 +0x51b

goroutine 2 [runnable]:
runtime.forcegchelper()
    /usr/lib/go/src/runtime/proc.go:90
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 3 [runnable]:
runtime.bgsweep()
    /usr/lib/go/src/runtime/mgc0.go:82
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 4 [runnable]:
runtime.runfinq()
    /usr/lib/go/src/runtime/malloc.go:712
runtime.goexit()
    /usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by mewmew** [comment]
> Gets a runtime error:

Oh, wow. This should definitely not happen ^^ _No matter how many test cases you implement, bror always finds a way to break it_ <3

**Comment by mewmew** [comment]
Btw, sms'ade Danne dig? Har du lust kan du messa honom att han kan lufsa över till Hagsätra. Jag insåg just att klockan bara var 3pm, så rör mig nog först om 2h.

**Comment by mewmew** [comment]
> Btw, sms'ade Danne dig? Har du lust kan du messa honom att han kan lufsa över till Hagsätra. Jag insåg just att klockan bara var 3pm, så rör mig nog först om 2h.

Disregard det jag just sa. Jag är fortfarande på Greenwich time. Det är lättast att jag möter upp honom på Långängsvägen skulle jag tro. Rör mig här ifrån om ca 1h.

**Comment by mewmew** [comment]
Commit a095e8b14cfbb940d84b6f7fef1f39a300b91997 fixes https://github.com/decomp/decomp/issues/175#issuecomment-221145635. The original issue reported is yet to be fixed however.

**Comment by mewmew** [comment]
Fixed in commit https://github.com/decomp/decomp/commit/9c5bf088d1d31aa380fc883e2ae17fc0df410de5
