### ISSUE TITLE
cmd/restructure: Crash when replacing entry node.

### ISSUE THREAD

**Issue by mewmew** [decomp/decomp#177]
_From @mewmew on May 29, 2015 9:27_

Stack trace:

```
[~/Desktop/go/src/decomp.org/x/graphs/testdata/c4_graphs/]$ restructure -steps -img expr.dot 
2015/05/29 09:53:55 Creating: "expr_1a.dot"
2015/05/29 09:53:55 Creating: "expr_1a.png"
2015/05/29 09:54:00 Creating: "expr_1b.dot"
2015/05/29 09:54:00 Creating: "expr_1b.png"
2015/05/29 09:54:08 Creating: "expr_2a.dot"
2015/05/29 09:54:08 Creating: "expr_2a.png"
2015/05/29 09:54:16 Creating: "expr_2b.dot"
2015/05/29 09:54:16 Creating: "expr_2b.png"
...
2015/05/29 10:04:53 Creating: "expr_31a.dot"
2015/05/29 10:04:53 Creating: "expr_31a.png"
2015/05/29 10:05:02 Creating: "expr_31b.dot"
2015/05/29 10:05:02 Creating: "expr_31b.png"
2015/05/29 10:05:09 Creating: "expr_32a.dot"
2015/05/29 10:05:09 Creating: "expr_32a.png"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x4a9b2c]

goroutine 1 [running]:
github.com/mewfork/dot.buildDomTree(0xc208127440)
    /home/u/Desktop/go/src/github.com/mewfork/dot/dom.go:163 +0x49c
github.com/mewfork/dot.(*Graph).Replace(0xc208127440, 0xc20847c700, 0x3, 0x4, 0xc208141980, 0xa, 0xc2080cdc00, 0xc2080cdd80, 0x0, 0x0)
    /home/u/Desktop/go/src/github.com/mewfork/dot/graph.go:101 +0x690
decomp.org/x/graphs/merge.Merge(0xc208127440, 0xc208479c50, 0xc2080f25a0, 0xc208141980, 0xa, 0x0, 0x0)
    /home/u/Desktop/go/src/decomp.org/x/graphs/merge/merge.go:32 +0x827
main.findPrim(0xc208127440, 0xc208017540, 0x6, 0xa, 0x20, 0xc208535410, 0x0, 0x0)
    /home/u/Desktop/go/src/decomp.org/x/cmd/restructure/restructure.go:295 +0x9df
main.restructure(0x7ffdb9574c2f, 0x8, 0xc208017540, 0x6, 0xa, 0xc20800c480, 0x1f, 0x30, 0x0, 0x0)
    /home/u/Desktop/go/src/decomp.org/x/cmd/restructure/restructure.go:238 +0x3bb
main.main()
    /home/u/Desktop/go/src/decomp.org/x/cmd/restructure/restructure.go:155 +0x265
```
- [expr_32a.dot](https://gist.githubusercontent.com/mewmew/b8cbce0c3a0065cd2abd/raw/41a81f2fd88a2009605656798c802098bc40d1b2/expr_32a.dot): Pre-merge control flow graph with highlighted nodes for replacement which caused the crash:

![pre-merge CFG](http://i.imgur.com/py1gVzM.jpg)

Thanks to @pfalcon for suggesting to output intermediate CFGs during the control flow recovery stage in decomp/decompilation#170! Current and future debugging sessions will be vastly facilitated by this feature.

_Copied from original issue: decomp/restructure#2_

**Comment by mewmew** [comment]
This issue has been resolved with the rewrite of the [restructure tool](https://godoc.org/github.com/decomp/decomp/cmd/restructure) (commit 4d16c3abf22ddeab66f6a527fa949596751953c7).

Specifically, the entry node is relocated after each identified primitive.

From [cmd/restructure/main.go:193](https://github.com/decomp/decomp/blob/1980434f92563233ea970f26785a0d2fb576d527/cmd/restructure/main.go#L193).

```go
		// Handle special case where entry node has been replaced by primitive
		// node.
		if !g.Has(entry) {
			entry = g.NodeByLabel(prim.Node)
			if entry == nil {
				return nil, errors.Errorf("unable to locate entry node %q", prim.Node)
			}
		}
```
