### ISSUE TITLE
[Error] make in demo folder

### ISSUE THREAD

**Issue by julyhuangzhou** [decomp/decomp#222]
HI,
after `go get`, I still can't use ll2dot.
 
I use LLVM 10, clang 10, go 1.13, and have installed graphviz on Ubuntu 18.04.
using command `go get github.com/decomp/decomp/cmd/...`, got following content
```
# gonum.org/v1/gonum/graph/iterator
/home/me/go/pkg/mod/gonum.org/v1/gonum@v0.9.0/graph/iterator/map.s: Assembler messages:
/home/me/go/pkg/mod/gonum.org/v1/gonum@v0.9.0/graph/iterator/map.s: 警告： 到达注释尾部；插入新行
```

and then, using command `go get github.com/decomp/exp/cmd/dot2png`, got following content 
```
go: finding github.com/decomp/exp latest
```
and then, run `make`
```
# * Step 1
#    - Produce control flow graphs for each function of the LLVM IR.
#
#    - input:  foo.ll
#    - output: foo_graphs/main.dot
ll2dot -f foo.ll
make: ll2dot: Command not found
Makefile:31: recipe for target 'foo.go' failed
make: *** [foo.go] Error 127
```

so what or how can I do?  
Best wishes

**Comment by mewmew** [comment]
Hi @julyhuangzhou,

Glad to see you are experimenting with LLVM IR decompilation :)

>  using command go get github.com/decomp/decomp/cmd/..., got following content

It seems that the installation instructions of `decomp` were still using the Go get approach. We've switched to using Go modules, I've now updated the [Installation](https://github.com/decomp/decomp#installation) section of the README accordingly.

```bash
git clone https://github.com/decomp/decomp
cd decomp
go install -v ./...
```

> and then, using command go get github.com/decomp/exp/cmd/dot2png, got following content

Try using:
```bash
go install -v github.com/decomp/exp/cmd/dot2png@master
```

Other dependencies of the demo:
```bash
go install -v github.com/mewkiz/cmd/sar@master
go install -v golang.org/x/tools/cmd/goimports@master
go install -v github.com/jackspirou/grind@master
```

I've included further details on how to install dependencies and how to run the demo in the README at: https://github.com/decomp/decomp/tree/master/examples/demo#demo

Check it out and let me know how it works :)

Wish you a happy weekend!

Cheers,
Robin

**Comment by julyhuangzhou** [comment]
Hi! @mewmew 
Thanks for the quick reply. When using command `go install -v ./...` ,error is given.
```
cmd/go-post/main.go:22:2: use of internal package not allowed
```
I guess internal packages can only be imported from packages rooted at the parent of the internal folder. But i don't how to deal with it.

Wish you have a nice day!

julyhuangzhou

**Comment by mewmew** [comment]
>  Thanks for the quick reply. When using command go install -v ./... ,error is given.

Hmm, I wonder if this has to do with the Go version. I am able to build successfully using Go 1.16. I think the way Go Modules are handled has been updated since Go 1.13.

Would you be able to update your Go version to the latest stable release and try to see if that fixes the issue?

Cheers,
Robin

**Comment by lcy19** [comment]
Hi, 
Although using go 1.16, there is something wrong, cause make is fail.  I tried on Ubuntu 18.04

$ go version 
> go version go1.16.5 linux/amd64

$ go install -v ./...
> github.com/decomp/decomp/cfa/primitive
github.com/decomp/decomp/cmd/go-post/internal/diff
github.com/decomp/decomp/graph/cfg
github.com/decomp/decomp/cmd/ll2dot
github.com/decomp/decomp/cmd/go-post
github.com/decomp/decomp/cfa
github.com/decomp/decomp/cmd/restructure
github.com/decomp/decomp/cmd/ll2go

cd to exeample/demo
$ make
>  \# * Step 0  
\#    - Convert original C source code to LLVM IR.  
\#  
\#    - input:  foo.c  
\#    - output: foo.ll  
clang -S -emit-llvm -o foo.ll foo.c  
opt -S --mem2reg -o foo.ll foo.ll  
\# * Step 1  
\#    - Produce control flow graphs for each function of the LLVM IR.  
\#  
\#    - input:  foo.ll  
\#    - output: foo_graphs/main.dot  
ll2dot -f foo.ll  
make: ll2dot: Command not found  
Makefile:13: recipe for target 'foo.go' failed  
make: *** [foo.go] Error 127  

thx for any suggestions

**Comment by mewmew** [comment]
The `ll2dot` command was successfully compiled, but does not seem to be in your `PATH` environment variable.

Try opening a terminal and running this line (assuming `ll2dot` was placed in the `$HOME/go/bin` directory, as is default in Go) before running `make` again in the demo directory.

```bash
export PATH=$PATH:$HOME/go/bin
make
```

Note, if you have GOPATH configured, then you should try to add `$GOPATH/bin` to `PATH`.
```bash
export PATH=$PATH:$GOPATH/bin
make
```

Let me know if it works.

Cheers,
Robin

**Comment by lcy19** [comment]
Thx, @mewmew, it works!
But _ll2go_ seems not support the c file contains `printf`, tested on hello.c as following,
```
#include <stdio.h>

int main(){
	int x = 10;
	printf("x = %d\n", x);
}
```

and outputs are
```
panic: support for value *constant.CharArray not yet implemented

goroutine 1 [running]:
main.(*decompiler).pointerToConst(0xc00013dd10, 0x78dac0, 0xc000030a40, 0x78d2e8, 0xc00000c348)
	/home/lcy/Downloads/decomp/cmd/ll2go/main.go:354 +0x869
main.(*decompiler).globalDecl(0xc00013dd10, 0xc000154000, 0x7ffcd363a1d5)
	/home/lcy/Downloads/decomp/cmd/ll2go/main.go:307 +0xb0
main.ll2go(0x7ffcd363a1d5, 0x7, 0xc00013deb0, 0x1, 0x0, 0x0)
	/home/lcy/Downloads/decomp/cmd/ll2go/main.go:141 +0x64b
main.main()
	/home/lcy/Downloads/decomp/cmd/ll2go/main.go:99 +0x328
```

so _ll2go_ now support what, or what type *.ll files can I use ll2go? 

thx for your advice.

**Comment by mewmew** [comment]
> Thx, @mewmew, it works!

Glad to see it works now :)

>  But ll2go seems not support the c file contains printf, tested on hello.c as following,

Yeah, the decomp support is still very early (see #221 for `CharArray` issue). For larger programs, I would recommend other decompilers :) `decomp` is more of an experimental decompilation pipeline than a production ready decompiler.

A few decompilers to try out if you feel adventurous:

* [reko](https://github.com/uxmal/reko) by @uxmal
   - Reko has LLVM IR support as well
* [Ghidra](https://ghidra-sre.org/)
   - There are project utilizing Ghidra IR to lift to LLVM IR, e.g. https://github.com/toor-de-force/Ghidra-to-LLVM
* [Anvill](https://github.com/lifting-bits/anvill) by Trail of Bits
   - binary -> LLVM RI
* [Rellic](https://github.com/lifting-bits/rellic) by Trail of Bits
   - LLVM IR -> C

There are many more, but this should be enough to get started :)

Wish you all the best and happy reverse engineering adventures!

Cheers,
Robin
